version: 2
jobs:
  build:
    docker:
      - image: cimg/node:18.20.8
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            npm install -g newman
            npm install -g newman-reporter-htmlextra

      - run:
          name: Run Newman tests
          command: |
            newman run HW4.postman_collection.json -e ClickUpHW.postman_environment.json -r htmlextra --reporter-htmlextra-export result/testHtmldev.html
      - store_artifacts:
          path: result/testHtmldev.html
          destination: reports/