name: Newman extra-html-report deploy to github page 

on: push

jobs:
  automated-test-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create dir
        run: |
          mkdir -p testResults

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
        
      - name: Install newman
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra

      - name: Run tests
        run: |
          newman run HW4.postman_collection.json -e ClickUpHW.postman_environment.json -r htmlextra --reporter-htmlextra-export testResults/htmlreport.html

      - name: Output the results
        uses: actions/upload-artifact@v4
        with:
          name: Reporter
          path: testResults

      - name: Get history
        uses: actions/checkout@v2
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Publish Github Pages
        if: ${{ always() }}
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: results-history
          keep_files: true 
